services:
  upsmanager:
    build: https://github.com/datagutten/upsmanager.git
    restart: unless-stopped
    volumes:
    - static_volume:/home/app/web/static
    networks:
    - proxy
    labels:
    - traefik.enable=true
    - traefik.docker.network=proxy
    - traefik.http.routers.upsmanager.rule=Host(`${DOMAIN}`) && PathPrefix(`/upsmanager`) && !PathPrefix(`/upsmanager/static`)
    - traefik.http.routers.upsmanager2.rule=Host(`upsmanager.${DOMAIN}`) && !PathPrefix(`/static`)
    - traefik.http.routers.upsmanager.middlewares=compress@file,upsmanager-strip
    - traefik.http.routers.upsmanager.tls=true
    - traefik.http.routers.upsmanager.tls.certresolver=monitor
    - traefik.http.middlewares.upsmanager-strip.stripprefix.prefixes=/upsmanager
    env_file:
    - .env

  apache:
    image: httpd:2.4
    restart: unless-stopped
    volumes:
    - static_volume:/usr/local/apache2/htdocs/upsmanager/static

    labels:
    - traefik.enable=true
    - traefik.docker.network=proxy
    - traefik.http.routers.upsmanager_static.rule=Host(`${DOMAIN}`) && PathPrefix(`/upsmanager/static`)
    - traefik.http.routers.upsmanager_static.tls=true
    - traefik.http.routers.upsmanager_static.tls.certresolver=monitor
    networks:
    - proxy

volumes:
  static_volume:

networks:
  proxy:
    external: true