{
 "title": "Nettverkstrafikk VÅF",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frogn internettrafikk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.fk-coreswitch-1-02.ports.1_1_30.ifOutOctets,8)),1),\"Out\")"
    },
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.fk-coreswitch-1-02.ports.1_1_30.ifInOctets,8)),1),\"In\")"
    }
   ]
  },
  {
   "title": "Vestby internettrafikk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE01.ports.Ethernet1_17.ifOutOctets,8)),1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE01.ports.Ethernet1_17.ifInOctets,8)),1)"
    }
   ]
  },
  {
   "title": "Ås internettrafikk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.10_214_188_2.ports.ethernet1_1.ifOutOctets,8)),1),\"Out\")"
    },
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.10_214_188_2.ports.ethernet1_1.ifInOctets,8)),1),\"In\")"
    }
   ]
  },
  {
   "title": "Trafikk brannmur Ås",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.as-kjerneswitch.ports.Te1_7.ifInOctets, 8)), 1), 'In')"
    },
    {
     "source": "url",
     "target": "alias(scaleToSeconds(nonNegativeDerivative(scale(nav.devices.as-kjerneswitch.ports.Te1_7.ifOutOctets, 8)), 1), 'Out')",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Vestby trafikk CORE01",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE01.ports.Ethernet*.ifOutOctets,8)),1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE01.ports.Ethernet*.ifInOctets,8)),1)"
    }
   ]
  },
  {
   "title": "Vestby trafikk CORE02",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE02.ports.Ethernet*.ifOutOctets,8)),1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.RAH-CORE02.ports.Ethernet*.ifInOctets,8)),1)"
    }
   ]
  },
  {
   "title": "Vestby trafikk WAN1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.WAN1*.ports.Twe*.ifOutOctets,8)),1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.WAN1.no.ports.Twe*.ifInOctets,8)),1)"
    }
   ]
  },
  {
   "title": "Vestby trafikk WAN2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.WAN2.ports.Twe1*.ifOutOctets,8)),1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.WAN2.ports.Twe1*.ifInOctets,8)),1)"
    }
   ]
  },
  {
   "title": "Vestby trafikk WAN1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.VKSW-VBS01.ports.Te*.ifOutOctets, 8)), 1)"
    },
    {
     "target": "scaleToSeconds(nonNegativeDerivative(scale(nav.devices.VKSW-VBS01.ports.Te*.ifInOctets,8)),1)"
    }
   ]
  }
 ]
}