{
 "title": "Temperatur og fuktighet serverrom",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Temperatur serverrack Vestby",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "target": "nav.devices.10_176_2_201.sensors.CMCIII-HUM_Temperature_Value"
    }
   ]
  },
  {
   "title": "Fuktighet serverrack Vestby",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "target": "nav.devices.10_176_2_201.sensors.CMCIII-HUM_Humidity_Value"
    }
   ]
  },
  {
   "title": "Temperatur serverrom Ås",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "source": "url",
     "target": "nav.devices.SP017277.sensors.temperature0",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Fuktighet serverrom Ås",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "source": "url",
     "target": "nav.devices.SP017277.sensors.humidity0",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Temperatur UPS-rom Ås",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "source": "url",
     "target": "nav.devices.SP017277.sensors.temperature1",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Fuktighet UPS-rom Ås",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "target": "nav.devices.SP017277.sensors.humidity1"
    }
   ]
  }
 ]
}