x-log: &loki-logging
    logging:
      driver: loki
      options:
        loki-url: "http://loki/loki/api/v1/push"
        loki-retries: "10"
        loki-batch-size: "9400"

version: "3"
services:
# Prometheus https://hub.docker.com/r/prom/prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    pull_policy: always
    restart: unless-stopped
    networks:
      - proxy
      - monitor-net
#    ports:
#      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=180d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
      - --web.external-url=https://service.${DOMAIN}/prometheus/
      - --web.enable-admin-api
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.prometheus.rule=Host(`service.${DOMAIN}`) && PathPrefix(`/prometheus`)
      - traefik.http.routers.prometheus.middlewares=users-auth@file
      - traefik.http.routers.prometheus.tls=true
      - traefik.http.routers.prometheus.tls.certresolver=monitor
      - org.label-schema.group=monitoring
    volumes:
      - ./data/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    environment:
      - TZ=Europe/Oslo
#    <<: *loki-logging

# Prometheus node exporter https://hub.docker.com/r/prom/node-exporter
  nodeexporter:
    container_name: nodeexporter
    image: prom/node-exporter
    pull_policy: always
    restart: unless-stopped
    depends_on:
      - prometheus
    networks:
      - monitor-net
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
#      - /run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
#      - --collector.systemd
      - --collector.processes
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
    labels:
      - org.label-schema.group=monitoring
    environment:
      - TZ=Europe/Oslo
#    <<: *loki-logging

networks:
  proxy:
    external: true
  monitor-net:
    external: true
volumes:
  prometheus-data: