services:
  # Grafana
  grafana:
    container_name: grafana
    image: grafana/grafana
    pull_policy: always
    restart: unless-stopped
    networks:
      - proxy
      - monitor-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.grafana.rule=Host(`${DOMAIN}`) && PathPrefix(`/grafana`)
      - traefik.http.routers.grafana.middlewares=compress@file
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=monitor
    env_file:
      - .env
    environment:
      #      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      #      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      #      - GF_LOG_FILTERS=rendering:debug
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_SERVER_ROOT_URL=https://${DOMAIN}/grafana
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_INSTALL_PLUGINS=yesoreyeram-infinity-datasource
      - TZ=Europe/Oslo
    volumes:
      - ${DATA_PATH}/grafana:/var/lib/grafana
      - ./data/provisioning:/var/lib/grafana/provisioning
    extra_hosts:
      - "nav.as.kommune.no:10.214.118.80"
      - "nav-core.as.kommune.no:10.1.110.203"
      - "nav.frogn.kommune.no:10.100.252.72"
      - "nav.vestby.kommune.no:10.211.3.223"
      - "sftool.storfollo.local:10.100.252.65"

networks:
  proxy:
    external: true
  monitor-net:
    external: true


volumes:
  grafana-data:
    external: true