services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongodb:
    image: mongo:6.0.14
    pull_policy: always
    volumes:
      - ${DATA_PATH}/mongo_data:/data/db
    restart: "on-failure"
    networks:
      - graylog

  # OpenSearch: https://opensearch.org/docs/latest/install-and-configure/install-opensearch/docker/
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    pull_policy: always
    volumes:
      - ${DATA_PATH}/os_data:/usr/share/opensearch/data
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: "on-failure"
    networks:
      - graylog
      - monitor-net

  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:6.1
    pull_policy: always
    depends_on:
      mongodb:
        condition: "service_started"
      opensearch:
        condition: "service_started"

    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.graylog.rule=Host(`graylog.${DOMAIN}`)
      - traefik.http.routers.graylog.middlewares=compress@file
      - traefik.http.routers.graylog.tls=true
#      - traefik.http.routers.graylog.tls.certresolver=monitor
      - traefik.http.services.graylog.loadbalancer.server.port=9000
#      - traefik.http.routers.graylog.tls.domains[0].main=storfollo.no
#      - traefik.http.routers.graylog.tls.domains[0].sans=*.storfollo.no

    volumes:
      - ${DATA_PATH}/graylog_data:/usr/share/graylog/data
      # - ./plugin:/usr/share/graylog/plugin
    environment:
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    env_file:
    - ./.env
    entrypoint: /usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh
    links:
      - mongodb:mongo
      - opensearch
    restart: always
    networks:
    - graylog
    - proxy

    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      # Palo Alto
      #- "5555-5559:5555-5559"
      - 5556:5556
      - 5557-5558:5557-5558/udp

networks:
  graylog:
    driver: "bridge"
  proxy:
    external: true
  monitor-net:
    external: true


  # Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
    mongo_data:
      driver: local
    os_data:
      driver: local
    graylog_data:
      driver: local
