services:
  telegraf:
    container_name: telegraf
    image: telegraf
    pull_policy: always
    restart: unless-stopped
    networks:
    - monitor-net
    volumes:
    - ./data:/etc/telegraf/telegraf.d
    - ./data/mibs:/usr/share/snmp/mibs:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
    - ./.env


networks:
  monitor-net:
    external: true