x-log: &loki-logging
    logging:
      driver: loki
      options:
        loki-url: "https://loki:${LOKI_PASS}@loki.${DOMAIN}/loki/api/v1/push"
        loki-retries: "10"
        loki-batch-size: "9400"

services:
  semaphore-db:
    image: postgres:15-alpine
    pull_policy: always
    container_name: postgres
    restart: unless-stopped
    networks:
      - backend
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: semaphore
      TZ: Europe/Oslo
    labels:
      - org.label-schema.group=monitoring
    volumes:
      - db:/var/lib/postgresql/data
#    <<: *loki-logging

  # https://docs.semui.co/
  semaphore:
    image: semaphoreui/semaphore:latest
    pull_policy: always
    container_name: semaphore
    depends_on:
      - semaphore-db
    restart: unless-stopped
    expose:
      - 3000
    networks:
      - backend
      - proxy
    environment:
      SEMAPHORE_DB_USER: ${DB_USER}
      SEMAPHORE_DB_PASS: ${DB_PASS}
      SEMAPHORE_DB_HOST: postgres
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_PASS}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: ${EMAIL}
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION} #key for encrypting access keys in database. It must be generated by using the following command: head -c32 /dev/urandom | base64
      ANSIBLE_HOST_KEY_CHECKING: false
      TZ: Europe/Oslo
    volumes:
      - ./inventory/:/inventory:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.semaphore.rule=Host(`semaphore.${DOMAIN}`)
      - traefik.http.routers.semaphore.tls=true
      - traefik.http.routers.semaphore.tls.certresolver=basic
      - traefik.http.routers.semaphore.middlewares=users-auth@file
      - org.label-schema.group=monitoring
#    <<: *loki-logging

networks:
  proxy:
    external: true
  backend:
volumes:
  db: